### ISSUE TITLE
issue running the compiler

### ISSUE THREAD

**Issue by rpau** [rpau/javalang-compiler#6]
ERROR [main] - TRANSFORMATION CHAIN (main-chain) FAILS
An exeception has been produced during the walkmod:commons:unused-declarations-cleaner transformation - org.walkmod.util.location.LocationImpl@16008608
at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.walkmod.walkers.AbstractWalker.walk(AbstractWalker.java:260)
at org.walkmod.walkers.AbstractWalker.execute(AbstractWalker.java:275)
at org.walkmod.impl.DefaultChainWalkerInvocation.invoke(DefaultChainWalkerInvocation.java:42)
at org.walkmod.impl.DefaultChainInvocation.invoke(DefaultChainInvocation.java:38)
at org.walkmod.impl.DefaultChainAdapter.execute(DefaultChainAdapter.java:165)
at org.walkmod.WalkModFacade.executeAllChains(WalkModFacade.java:518)
at org.walkmod.WalkModFacade.apply(WalkModFacade.java:266)
at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:181)
Caused by: java.lang.reflect.InvocationTargetException
... 11 more
Caused by: java.lang.NullPointerException
at org.walkmod.javalang.compiler.symbols.SymbolVisitorAdapter.visit(SymbolVisitorAdapter.java:185)
at org.walkmod.javalang.compiler.symbols.SymbolVisitorAdapter.visit(SymbolVisitorAdapter.java:91)
at org.walkmod.javalang.ast.expr.NormalAnnotationExpr.accept(NormalAnnotationExpr.java:54)
at org.walkmod.javalang.visitors.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:175)
at org.walkmod.javalang.ast.expr.ArrayInitializerExpr.accept(ArrayInitializerExpr.java:50)
at org.walkmod.javalang.visitors.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:519)
at org.walkmod.javalang.ast.expr.MemberValuePair.accept(MemberValuePair.java:53)
at org.walkmod.javalang.visitors.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:575)
at org.walkmod.javalang.compiler.symbols.SymbolVisitorAdapter.visit(SymbolVisitorAdapter.java:186)

**Comment by rpau** [comment]
Solved in master
